2022-08-01 14:57:15,817 - example.py:17 - Start
2022-08-01 14:57:15,817 - example.py:22 - Exception
Traceback (most recent call last):
  File ".\example.py", line 20, in <module>
    add_one(dt_business_date=args[1])
TypeError: add_one() got an unexpected keyword argument 'dt_business_date'
2022-08-01 14:57:15,820 - example.py:25 - End
2022-08-01 14:57:28,045 - example.py:17 - Start
2022-08-01 14:57:28,046 - example.py:6 - Start
2022-08-01 14:57:28,046 - example.py:10 - Exception
Traceback (most recent call last):
  File ".\example.py", line 8, in add_one
    return number + 2
TypeError: can only concatenate str (not "int") to str
2022-08-01 14:57:28,047 - example.py:12 - End
2022-08-01 14:57:28,047 - example.py:25 - End
2022-08-01 14:58:16,287 - example.py:17 - Start
2022-08-01 14:58:16,287 - example.py:6 - Start
2022-08-01 14:58:16,287 - example.py:12 - End
2022-08-01 14:58:16,295 - example.py:25 - End
2022-08-01 14:58:39,178 - example.py:17 - Start
2022-08-01 14:58:39,178 - example.py:6 - Start
2022-08-01 14:58:39,178 - example.py:12 - End
2022-08-01 14:58:39,179 - example.py:26 - End
2022-08-01 14:58:43,315 - example.py:17 - Start
2022-08-01 14:58:43,315 - example.py:6 - Start
2022-08-01 14:58:43,316 - example.py:12 - End
2022-08-01 14:58:43,316 - example.py:26 - End
